global:
  projectName: ampere
  namespace: ampere
  storageClass: local-path
  kubeVersion: "1.31"
networking:
  calicoCidr: 10.10.0.0/16
  masterIp: 192.168.11.100
nodes:
  postgresql: 192.168.11.101
  minio: 192.168.11.102
  airflow: 192.168.11.103
