namespace: ampere
replicaCount: 1
image:
  repository: quay.io/minio/minio
  tag: RELEASE.2025-07-23T15-54-02Z
service:
  type: NodePort
  ports:
    - name: s3
      port: 9000
      targetPort: 9000
      nodePort: 30091
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 30090
resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"
persistence:
  size: 5Gi
  storageClassName: local-path
users:
  - accessKey: externalSecret
    existingSecret: minio-creds
nodeSelector:
  kubernetes.io/hostname: ampere-k8s-node2
