apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "postgresql.name" .) }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgresql
      port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: postgresql
  selector:
    app.kubernetes.io/name: {{ include "postgresql.name" . }}
