namespace: ${PROJECT_NAME}

mssql:
  image: $MSSQL_IMAGE
  nodePort: ${MSNODE_NODEPORT}
  storage: 10Gi
  secretName: mssql-sa-secret
  pvcName: mssql-pvc
  serviceName: mssql-service
  nodeSelector:
    kubernetes.io/hostname: ${NODE1_NAME}